### ISSUE TITLE
Pass model instead of ViewData

### ISSUE THREAD

**Issue by ClaribelMendez** [ClaribelMendez/dotnetNewProject#7]
In PlayerInfo.cshtml

**Comment by ClaribelMendez** [comment]
This was reviewed during our pair session, it has been resolved.

**Comment by KyleMit** [comment]
I think this is actually being handled in PR #8 

The standard is gonna be that you leave the issue open until the PR is merged.  Also, you can write `Fixes #7` in the body of the PR and it'll automatically link the two.  That way when closing issues, we can identify what code is changing that solves the issue.
